### ISSUE TITLE
403 ERROR

### ISSUE THREAD

**Issue by FBeraZulaloglu** [keremkoseoglu/luta#10]
Yeni sürümde herhalde chrome veya safari için web driver path bakmıyor. Aynı zamanda 403 error yüzünden sahibinden den veri çekilemiyor. Bunu nasıl güncellememiz gerekir acaba ?

**Comment by keremkoseoglu** [comment]
Selamlar, Luta'nın kullanıldığı sahibinden projesini arşivledim, artık güncellemiyorum ve desteklemiyorum. Aldığınız hatayı sadece sahibinden'de mi aldınız, başka sitelerde de alıyor musunuz?

**Comment by keremkoseoglu** [comment]
Cevap alamadığım için, maddeyi kapatıyorum.
